version: "2"

services:
  web:
    image: chrisb.azurecr.io/superspork/web:latest
    ports:
     - 9000:8080
     - 9001:8081
  api:
    image: chrisb.azurecr.io/superspork/api:latest
    ports:
     - 9002:8080
  elasticsearch:
    image: chrisb.azurecr.io/superspork/elasticsearch:latest
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata:
    driver: local
