apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
      nodePort: 32010
  selector:
    app: superspork-elasticsearch
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: superspork-elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: superspork-elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - image: chrisb.azurecr.io/superspork/elasticsearch:latest
        name: superspork-elasticsearch
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
      imagePullSecrets:
      - name: regsecret
