apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.99.1
    path: "/elasticsearch"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-elasticsearch-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
