apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32000
      name: web-public
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 32001
      name: web-management
  selector:
    app: superspork-web
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: superspork-web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: superspork-web
    spec:
      containers:
      - image: chrisb.azurecr.io/superspork/web:0.0.3
        name: superspork-web
        ports:
        - containerPort: 8080
          name: public-web
        - containerPort: 8081
          name: management
        readinessProbe:
          httpGet:
            path: /manage/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /manage/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 3
      imagePullSecrets:
      - name: regsecret
