apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32001
  selector:
    app: superspork-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: superspork-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: superspork-api
    spec:
      containers:
      - image: chrisb.azurecr.io/superspork/api:latest
        name: superspork-api
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regsecret
