apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32000
  selector:
    app: superspork-web
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: superspork-web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: superspork-web
    spec:
      containers:
      - image: chrisb.azurecr.io/superspork/web:latest
        name: superspork-web
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regsecret
