apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32010
      name: api-public
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 32011
      name: api-management
  selector:
    app: superspork-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: superspork-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: superspork-api
    spec:
      containers:
      - image: chrisb.azurecr.io/superspork/api:0.0.2
        name: superspork-api
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 8081
          name: management
      imagePullSecrets:
      - name: regsecret
